name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container & Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: polarizedions/weather2png/weather2png
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,v1.${{ github.run_number }}"
